# Generated by Django 3.1.3 on 2020-12-02 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Heats', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='', verbose_name='guideline/')),
                ('order', models.IntegerField(default=0)),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Heats.heat')),
            ],
        ),
    ]
