# Generated by Django 3.1.3 on 2020-11-19 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Heats', '0001_initial'),
        ('User', '0004_auto_20201119_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('confirm_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('MB', 'Membership Payment'), ('EC', 'Earning Commission')], max_length=2)),
                ('heat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Heats.heat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.baseuser')),
            ],
        ),
    ]
