# Generated by Django 3.1.3 on 2020-11-08 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Heats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('confirm_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('EC', 'Earning Commission'), ('MB', 'Membership Payment')], max_length=2)),
                ('heat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Heats.heat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
