# Generated by Django 3.1.3 on 2020-11-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MB', 'Membership Payment'), ('EC', 'Earning Commission')], max_length=2),
        ),
    ]
