# Generated by Django 3.1.3 on 2020-11-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_auto_20201118_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('EC', 'Earning Commission'), ('MB', 'Membership Payment')], max_length=2),
        ),
    ]
