# Generated by Django 3.1.3 on 2020-11-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201108_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'User'), ('3', 'NFN Leader'), ('4', 'NFN Admin'), ('2', 'NFN Worker')], max_length=1),
        ),
    ]
