# Generated by Django 3.1.3 on 2020-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201119_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.CharField(choices=[('3', 'Other'), ('2', 'Female'), ('1', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('3', 'NFN Leader'), ('1', 'User'), ('2', 'NFN Worker'), ('4', 'NFN Admin')], default='1', max_length=1),
        ),
    ]
