# Generated by Django 3.1.3 on 2020-11-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201118_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='fb_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile-image'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'User'), ('3', 'NFN Leader'), ('4', 'NFN Admin'), ('2', 'NFN Worker')], default='1', max_length=1),
        ),
    ]
