# Generated by Django 3.1.3 on 2020-12-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201119_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.CharField(choices=[('2', 'Female'), ('1', 'Male'), ('3', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'User'), ('2', 'NFN Worker'), ('4', 'NFN Admin'), ('3', 'NFN Leader')], default='1', max_length=1),
        ),
    ]
